name: Create and publish image

on: push

env:
  REGISTRY: 593291632749.dkr.ecr.eu-west-1.amazonaws.com
  IMAGE_NAME: "analytical-platform-scheduler"
jobs:
  build-and-push-image:
    runs-on: [self-hosted, management-ecr]
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::593291632749:role/github-actions-management-ecr
          role-duration-seconds: 1200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 593291632749

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}

      - name: Bump version and push tag
        id: tag
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: anothrNick/github-tag-action@1.55.0 
        env:
          DEFAULT_BUMP: "patch"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: "ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.new_tag }}"
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
