name: Create and publish image

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: 593291632749.dkr.ecr.eu-west-1.amazonaws.com
  IMAGE_NAME: "analytical-platform-scheduler"
jobs:
  build-and-push-image:
    runs-on: [self-hosted, management-ecr]
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::593291632749:role/github-actions-management-ecr
          role-duration-seconds: 1200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 593291632749

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: type=semver,pattern={{major}}.{{minor}}.{{patch}}
          images: name=${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
